file=open("tops1.txt","w")
file.write("this is file management demo using python")
file.close()
print("file successfully created")
print("***********************************************************")
file=open("tops1.txt","r")
print(file.read())
file.close()
print("***********************************************************")
file=open("tops1.txt","a")
file.write("\n this is now appendend ")
file.close()
print("file successfully appended")
print("***********************************************************")
file=open("tops1.txt","r")
print(file.read())
file.close()
print("***********************************************************")
file=open("tops2.txt","w+")
file.write("this is w+ mode of file management")
file.seek(0)
print(file.read())
file.close()