# Generated by Django 5.1.3 on 2024-11-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_employee_deptno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
    ]
